import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(500000);

  await page.goto('https://leetcode.com/');
  await page.locator('#landing-page-app a').filter({ hasText: 'Explore' }).click();
  await page.locator('#landing-page-app a').filter({ hasText: 'Explore' }).click();
  await page.goBack();
  await page.goForward();
  await page.reload();
  await page.locator('a').filter({ hasText: 'Developer' }).click();
  await page.locator('#landing-page-app a').filter({ hasText: 'Explore' }).click();
  await page.getByRole('link', { name: 'Get Started' }).click();
  await page.getByRole('link', { name: 'Contest' }).click();
  await page.getByRole('link', { name: 'Problems' }).click();
  await page.getByRole('link', { name: 'Two Sum 56.2% Easy' }).click();
  await page.locator('.view-lines > div:nth-child(5)').click();
  await page.locator('#editor').getByRole('code').locator('div').filter({ hasText: 'vector<int> twoSum(vector<int' }).nth(4).click();
  await page.locator('#editor').getByRole('code').locator('div').filter({ hasText: 'vector<int> twoSum(vector<int' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums)       \n    }\n};');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums){\n    if(target-i)\n }       \n    }\n};');
  await page.getByText('(target-i').click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums){\n    if(sets.count(target-i)\n }       \n    }\n};');
  await page.locator('#editor').getByRole('code').locator('div').filter({ hasText: 'if(sets.count(target-i)' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.locator('#editor').getByRole('code').locator('div').filter({ hasText: 'if(sets.count(target-i)' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums){\n    if(sets.count(target-i)){\n        return {i,target-i}\n    }\n }       \n');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums){\n    if(sets.count(target-i)){\n        return {i,target-i};\n    }\n }       \n');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n\n unordered_set<int> sets;\n for(int i:nums){\n    if(sets.count(target-i)){\n        return {i,target-i};\n    }\n }       return -1;\n');
  await page.getByRole('link', { name: 'log in / sign up' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Email or phone' }).click();
  await page.getByRole('textbox', { name: 'Email or phone' }).fill('pnmohithreddy@gmail.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.goto('https://leetcode.com/problems/two-sum/description/');
  await page.getByText('class Solution {public:').click();
});